name: publish

on:
  release:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

  EXAMPLE_BUCKET: ${{ secrets.EXAMPLE_BUCKET }}
  EXAMPLE_PREFIX: ${{ secrets.EXAMPLE_PREFIX }}

  TEST_BUCKET: ${{ secrets.TEST_BUCKET }}
  TEST_PREFIX: ${{ secrets.TEST_PREFIX }}
  TEST_SERVICE_ACCOUNT: ${{ secrets.TEST_SERVICE_ACCOUNT }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
    - uses: katyo/publish-crates@v1
      with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}