name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: 
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      EXAMPLE_BUCKET: ${{ secrets.EXAMPLE_BUCKET }}
      EXAMPLE_PREFIX: ${{ secrets.EXAMPLE_PREFIX }}

      TEST_BUCKET: ${{ secrets.TEST_BUCKET }}
      TEST_PREFIX: ${{ secrets.TEST_PREFIX }}
      TEST_SERVICE_ACCOUNT: ${{ secrets.TEST_SERVICE_ACCOUNT }}

    steps:
      - uses: actions/checkout@v2
      - name: fmt
        run: cargo fmt --all -- --check
      - name: clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: build
        run: cargo build --verbose
      - name: unit tests
        run: cargo test --lib --verbose